name: "Code Portal"
version: "1.0.2" #last digit # 0 indicate a development cycle in course.
author: "NIST Opensource"
title: Code Portal
description: "National Institute of Standards and Technology Opensource Code Portal "
theme: nist-software-theme

url: "https://software.nist.gov"
repo_url: "https://github.com/usnistgov/software"

# Google Analytics ID
google_analytics:
  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
twitter:
  username: NIST

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: usnistgov/software
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - nist-software-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
